name: Bug Report
description: Open an issue for a bug in ENFT
title: 'Bug Report Title'
labels: ['investigate']
assignees:
  - kenryu42
body:
  - type: input
    id: version
    attributes:
      label: ENFT Version
      description: What version of enft are you using? Before opening an issue, please make sure you are up to date.
      placeholder: x.y.z
    validations:
      required: true
  - type: textarea
    id: about-the-bug
    attributes:
      label: Describe the Problem
      description: Please describe what you expected to happen vs what did happen?
      placeholder: What happened?
    validations:
      required: true
  - type: input
    id: contract-address
    attributes:
      label: Contract Address
      description: Which NFT contract address caused this issue?
      placeholder: e.g 0x...
  - type: input
    id: transaction-hash
    attributes:
      label: Transaction Hash
      description: Which transaction hash caused this issue?
      placeholder: e.g 0x...
  - type: textarea
    id: code-snippet
    attributes:
      label: Code Snippet
      description: If possible, please include a **short and concise** code snippets that can reproduce this issue.
      placeholder: e.g. enft.debugTransaction({...})
      render: shell
  - type: textarea
    id: contract-abi
    attributes:
      label: Contract ABI
      description: If this involves a contract, please include any **concise and relevant** ABI fragments.
      placeholder: e.g. [ 'function balanceOf(address owner) view returns (uint)' ]
      render: shell
  - type: textarea
    id: errors
    attributes:
      label: Errors
      description: If there is an error, please include the **entire error** (redacting any sensitive information).
      placeholder: "e.g. Error: invalid name (code='INVALID_ARGUMENT, ...)"
      render: shell
  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: What environment, platforms or frameworks are you using? Select all that apply.
      multiple: true
      options:
        - node.js (v16 or newer)
        - node.js (older than v16)
        - Other (please specify)
  - type: input
    id: other-envrionment
    attributes:
      label: Environment (Other)
      placeholder: anything else?
