name: Feature Request
description: Suggest a new feature or addition to ENFT
title: 'Feature Request Title'
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        The best place to start a new feature request is by starting an [Idea discussion](https://github.com/kenryu42/ethereum-nft-sales-bot/discussions), to mull over the feature, discuss current options and think through the impact on the overall library.

        Keep in mind that features increase the library size, and may require additional dependencies.
  - type: textarea
    id: about-the-feature
    attributes:
      label: Describe the Feature
      description: Please describe the feature, the problem it is solving, your solution and alternatives you've considered.
      placeholder: e.g. I want ENFT to be more/less magical.
    validations:
      required: true
  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: Optionally, provide an example of how the feature would be used in code.
      placeholder: e.g. enft.doMagic()
      render: shell
